classDiagram
    Place --> Place
    Place --> AdditionalProperties
    StopPoint --> Place
    StopPoint --> LineModeGroup
    StopPoint --> Identifier
    StopPoint --> LineGroup
    StopPoint --> AdditionalProperties
    RouteSectionNaptanEntrySequence --> StopPoint
    RouteSection --> RouteSectionNaptanEntrySequence
    Disruption --> StopPoint
    Disruption --> RouteSection
    LineStatus --> ValidityPeriod
    LineStatus --> Disruption
    Line --> MatchedRoute
    Line --> LineStatus
    Line --> Crowding
    Line --> Disruption
    Line --> LineServiceTypeInfo
    MatchedStop --> Identifier
    StopPointSequence --> MatchedStop
    RouteSequence --> StopPointSequence
    RouteSequence --> MatchedStop
    RouteSequence --> OrderedRoute
    RouteSearchMatch --> MatchedRouteSections
    RouteSearchMatch --> MatchedStop
    RouteSearchMatch --> LineRouteSection
    RouteSearchResponse --> RouteSearchMatch
    StationInterval --> Interval
    Period --> TwentyFourHourClockTime
    Period --> ServiceFrequency
    Schedule --> Period
    Schedule --> KnownJourney
    TimetableRoute --> Schedule
    TimetableRoute --> StationInterval
    Timetable --> TimetableRoute
    Disambiguation --> DisambiguationOption
    TimetableResponse --> Timetable
    TimetableResponse --> Disambiguation
    TimetableResponse --> MatchedStop
    Prediction --> PredictionTiming
    Crowding --> TrainLoading
    Crowding --> PassengerFlow
    Identifier --> Crowding
    CarParkOccupancy --> Bay
    SearchResponse --> SearchMatch
    LineSpecificServiceType --> LineServiceTypeInfo
    LineServiceType --> LineSpecificServiceType
    ArrivalDeparture --> PredictionTiming
    StopPointsResponse --> StopPoint
    Path --> JpElevation
    Path --> Identifier
    RouteOption --> Identifier
    Leg --> Point
    Leg --> RouteOption
    Leg --> Identifier
    Leg --> Path
    Leg --> Obstacle
    Leg --> Instruction
    Leg --> Disruption
    Leg --> PlannedWork
    FareTap --> FareTapDetails
    Fare --> FareTap
    JourneyFare --> FareCaveat
    JourneyFare --> Fare
    Journey --> JourneyFare
    Journey --> Leg
    InstructionStep --> PathAttribute
    TimeAdjustments --> TimeAdjustment
    SearchCriteria --> TimeAdjustments
    Instruction --> InstructionStep
    ItineraryResult --> Line
    ItineraryResult --> Journey
    ItineraryResult --> JourneyVector
    ItineraryResult --> SearchCriteria
    ItineraryResult --> JourneyPlannerCycleHireDockingStationData
    AccidentDetail --> Casualty
    AccidentDetail --> Vehicle
    DbGeography --> DbGeographyWellKnownValue
    Street --> StreetSegment
    RoadDisruptionLine --> DbGeography
    RoadDisruptionImpactArea --> DbGeography
    RoadDisruption --> DbGeography
    RoadDisruption --> RoadDisruptionImpactArea
    RoadDisruption --> RoadDisruptionLine
    RoadDisruption --> RoadDisruptionSchedule
    RoadDisruption --> RoadProject
    RoadDisruption --> Street
    ArrayOfModes --> Mode
    ArrayOfStatusSeverities --> StatusSeverity
    ArrayOfLines --> Line
    ArrayOfStopPoints --> StopPoint
    ArrayOfDisruptions --> Disruption
    ArrayOfPredictions --> Prediction
    ArrayOfActiveServiceTypes --> ActiveServiceType
    ArrayOfPlaceCategories --> PlaceCategory
    ArrayOfPlaces --> Place
    AccidentDetailArray --> AccidentDetail
    ArrayOfLiftDisruptions --> LiftDisruption
    ArrayOfRoadCorridors --> RoadCorridor
    ArrayOfRoadDisruptions --> RoadDisruption
