classDiagram
    RouteSequence --> OrderedRoute
    RouteSequence --> StopPointSequence
    RouteSequence --> MatchedStop
    RouteSearchResponse --> RouteSearchMatch
    TimetableResponse --> Timetable
    TimetableResponse --> Disambiguation
    TimetableResponse --> MatchedStop
    CarParkOccupancy --> Bay
    SearchResponse --> SearchMatch
    LineServiceType --> LineSpecificServiceType
    ArrivalDeparture --> PredictionTiming
    StopPointsResponse --> StopPoint
    ItineraryResult --> Line
    ItineraryResult --> JourneyVector
    ItineraryResult --> SearchCriteria
    ItineraryResult --> Journey
    ItineraryResult --> JourneyPlannerCycleHireDockingStationData
    ArrayOfModes --> Mode
    ArrayOfStatusSeverities --> StatusSeverity
    ArrayOfLines --> Line
    ArrayOfStopPoints --> StopPoint
    ArrayOfDisruptions --> Disruption
    ArrayOfPredictions --> Prediction
    ArrayOfActiveServiceTypes --> ActiveServiceType
    ArrayOfPlaceCategories --> PlaceCategory
    ArrayOfPlaces --> Place
    AccidentDetailArray --> AccidentDetail
    ArrayOfLiftDisruptions --> LiftDisruption
    ArrayOfRoadCorridors --> RoadCorridor
    ArrayOfRoadDisruptions --> RoadDisruption
    StopPointSequence --> MatchedStop
    RouteSearchMatch --> MatchedRouteSections
    RouteSearchMatch --> MatchedStop
    RouteSearchMatch --> LineRouteSection
    Timetable --> TimetableRoute
    Disambiguation --> DisambiguationOption
    LineSpecificServiceType --> LineServiceTypeInfo
    SearchCriteria --> TimeAdjustments
    Journey --> JourneyFare
    Journey --> Leg
    Line --> LineStatus
    Line --> MatchedRoute
    Line --> Disruption
    Line --> LineServiceTypeInfo
    Line --> Crowding
    Prediction --> PredictionTiming
    AccidentDetail --> Vehicle
    AccidentDetail --> Casualty
    RoadDisruption --> RoadDisruptionSchedule
    RoadDisruption --> DbGeography
    RoadDisruption --> RoadProject
    RoadDisruption --> Street
    RoadDisruption --> RoadDisruptionLine
    RoadDisruption --> RoadDisruptionImpactArea
    MatchedStop --> Identifier
    TimetableRoute --> Schedule
    TimetableRoute --> StationInterval
    TimeAdjustments --> TimeAdjustment
    JourneyFare --> FareCaveat
    JourneyFare --> Fare
    Leg --> RouteOption
    Leg --> Instruction
    Leg --> Path
    Leg --> PlannedWork
    Leg --> Identifier
    Leg --> Disruption
    Leg --> Point
    Leg --> Obstacle
    LineStatus --> ValidityPeriod
    LineStatus --> Disruption
    Street --> StreetSegment
    RoadDisruptionLine --> DbGeography
    RoadDisruptionImpactArea --> DbGeography
    Schedule --> KnownJourney
    Schedule --> Period
    StationInterval --> Interval
    Fare --> FareTap
    RouteOption --> Identifier
    Instruction --> InstructionStep
    Path --> Identifier
    Path --> JpElevation
    Disruption --> StopPoint
    Disruption --> RouteSection
    DbGeography --> DbGeographyWellKnownValue
    Period --> ServiceFrequency
    Period --> TwentyFourHourClockTime
    FareTap --> FareTapDetails
    InstructionStep --> PathAttribute
    RouteSection --> RouteSectionNaptanEntrySequence
    RouteSectionNaptanEntrySequence --> StopPoint
    StopPoint --> Place
    StopPoint --> LineModeGroup
    StopPoint --> LineGroup
    StopPoint --> Identifier
    StopPoint --> AdditionalProperties
    Identifier --> Crowding
    Crowding --> TrainLoading
    Crowding --> PassengerFlow
    Place --> Place
    Place --> AdditionalProperties
