endpoints = {
    'Line_MetaModes': {'uri': '/Line/Meta/Modes', 'model': 'ArrayOfMode'},
    'Line_MetaSeverity': {'uri': '/Line/Meta/Severity', 'model': 'ArrayOfStatusSeverity'},
    'Line_MetaDisruptionCategories': {'uri': '/Line/Meta/DisruptionCategories', 'model': 'MetaServiceTypesGet200TextXmlResponse'},
    'Line_MetaServiceTypes': {'uri': '/Line/Meta/ServiceTypes', 'model': 'MetaServiceTypesGet200TextXmlResponse'},
    'Line_GetByPathIds': {'uri': '/Line/{ids}', 'model': 'ArrayOfLine'},
    'Line_GetByModeByPathModes': {'uri': '/Line/Mode/{modes}', 'model': 'ArrayOfLine'},
    'Line_RouteByQueryServiceTypes': {'uri': '/Line/Route', 'model': 'ArrayOfLine'},
    'Line_LineRoutesByIdsByPathIdsQueryServiceTypes': {'uri': '/Line/{ids}/Route', 'model': 'ArrayOfLine'},
    'Line_RouteByModeByPathModesQueryServiceTypes': {'uri': '/Line/Mode/{modes}/Route', 'model': 'ArrayOfLine'},
    'Line_RouteSequenceByPathIdPathDirectionQueryServiceTypesQueryExcludeCrowding': {'uri': '/Line/{id}/Route/Sequence/{direction}', 'model': 'RouteSequence'},
    'Line_StatusByPathIdsPathStartDatePathEndDateQueryDetail': {'uri': '/Line/{ids}/Status/{startDate}/to/{endDate}', 'model': 'ArrayOfLine'},
    'Line_StatusByIdsByPathIdsQueryDetail': {'uri': '/Line/{ids}/Status', 'model': 'ArrayOfLine'},
    'Line_SearchByPathQueryQueryModesQueryServiceTypes': {'uri': '/Line/Search/{query}', 'model': 'RouteSearchResponse'},
    'Line_StatusBySeverityByPathSeverity': {'uri': '/Line/Status/{severity}', 'model': 'ArrayOfLine'},
    'Line_StatusByModeByPathModesQueryDetailQuerySeverityLevel': {'uri': '/Line/Mode/{modes}/Status', 'model': 'ArrayOfLine'},
    'Line_StopPointsByPathIdQueryTflOperatedNationalRailStationsOnly': {'uri': '/Line/{id}/StopPoints', 'model': 'ArrayOfStopPoint'},
    'Line_TimetableByPathFromStopPointIdPathId': {'uri': '/Line/{id}/Timetable/{fromStopPointId}', 'model': 'TimetableResponse'},
    'Line_TimetableToByPathFromStopPointIdPathIdPathToStopPointId': {'uri': '/Line/{id}/Timetable/{fromStopPointId}/to/{toStopPointId}', 'model': 'TimetableResponse'},
    'Line_DisruptionByPathIds': {'uri': '/Line/{ids}/Disruption', 'model': 'ArrayOfDisruption'},
    'Line_DisruptionByModeByPathModes': {'uri': '/Line/Mode/{modes}/Disruption', 'model': 'ArrayOfDisruption'},
    'Line_ArrivalsWithStopPointByPathIdsPathStopPointIdQueryDirectionQueryDestina': {'uri': '/Line/{ids}/Arrivals/{stopPointId}', 'model': 'ArrayOfPrediction'},
    'Line_ArrivalsByPathIds': {'uri': '/Line/{ids}/Arrivals', 'model': 'ArrayOfPrediction'},
    'Forward_Proxy': {'uri': '/Line/*', 'model': 'Get200ApplicationJsonResponse'},
}
