classDiagram
    RouteSequence --> OrderedRoute
    RouteSequence --> MatchedStop
    RouteSequence --> StopPointSequence
    RouteSearchResponse --> RouteSearchMatch
    TimetableResponse --> Disambiguation
    TimetableResponse --> MatchedStop
    TimetableResponse --> Timetable
    CarParkOccupancy --> Bay
    SearchResponse --> SearchMatch
    StopPointsResponse --> StopPoint
    ItineraryResult --> JourneyPlannerCycleHireDockingStationData
    ItineraryResult --> SearchCriteria
    ItineraryResult --> JourneyVector
    ItineraryResult --> Journey
    ItineraryResult --> Line
    ModeArray --> Mode
    ArrayOfStatusSeverities --> StatusSeverity
    ArrayOfLine --> Line
    StopPointArray --> StopPoint
    ArrayOfDisruptions --> Disruption
    PredictionArray --> Prediction
    ArrayOfActiveServiceTypes --> ActiveServiceType
    PlaceCategoryArray --> PlaceCategory
    PlaceArray --> Place
    AccidentDetailArray --> AccidentDetail
    ArrayOfLiftDisruptions --> LiftDisruption
    ArrayOfRoadCorridors --> RoadCorridor
    ArrayOfRoadDisruptions --> RoadDisruption
    ChargeConnectorOccupancyArray --> ChargeConnectorOccupancy
    BikePointOccupancyArray --> BikePointOccupancy
    StopPointCategoryArray --> PlaceCategory
    LineServiceTypeArray --> LineServiceType
    ArrivalDepartureArray --> ArrivalDeparture
    StopPointRouteSectionArray --> StopPointRouteSection
    DisruptedPointArray --> DisruptedPoint
    StopPointSequence --> MatchedStop
    RouteSearchMatch --> MatchedRouteSections
    RouteSearchMatch --> MatchedStop
    RouteSearchMatch --> LineRouteSection
    Disambiguation --> DisambiguationOption
    Timetable --> TimetableRoute
    SearchCriteria --> TimeAdjustments
    Journey --> Leg
    Journey --> JourneyFare
    Line --> LineStatus
    Line --> MatchedRoute
    Line --> Disruption
    Line --> LineServiceTypeInfo
    Line --> Crowding
    Prediction --> PredictionTiming
    AccidentDetail --> Casualty
    AccidentDetail --> Vehicle
    RoadDisruption --> DbGeography
    RoadDisruption --> RoadProject
    RoadDisruption --> Street
    RoadDisruption --> RoadDisruptionLine
    RoadDisruption --> RoadDisruptionSchedule
    RoadDisruption --> RoadDisruptionImpactArea
    LineServiceType --> LineSpecificServiceType
    ArrivalDeparture --> PredictionTiming
    MatchedStop --> Identifier
    TimetableRoute --> StationInterval
    TimetableRoute --> Schedule
    TimeAdjustments --> TimeAdjustment
    Leg --> Instruction
    Leg --> PlannedWork
    Leg --> Obstacle
    Leg --> Identifier
    Leg --> RouteOption
    Leg --> Path
    Leg --> Disruption
    Leg --> Point
    JourneyFare --> Fare
    JourneyFare --> FareCaveat
    LineStatus --> ValidityPeriod
    LineStatus --> Disruption
    Street --> StreetSegment
    RoadDisruptionLine --> DbGeography
    RoadDisruptionImpactArea --> DbGeography
    LineSpecificServiceType --> LineServiceTypeInfo
    StationInterval --> Interval
    Schedule --> Period
    Schedule --> KnownJourney
    Instruction --> InstructionStep
    RouteOption --> Identifier
    Path --> Identifier
    Path --> JpElevation
    Fare --> FareTap
    Disruption --> StopPoint
    Disruption --> RouteSection
    DbGeography --> DbGeographyWellKnownValue
    Period --> ServiceFrequency
    Period --> TwentyFourHourClockTime
    InstructionStep --> PathAttribute
    FareTap --> FareTapDetails
    RouteSection --> RouteSectionNaptanEntrySequence
    RouteSectionNaptanEntrySequence --> StopPoint
    StopPoint --> LineModeGroup
    StopPoint --> AdditionalProperties
    StopPoint --> Identifier
    StopPoint --> LineGroup
    StopPoint --> Place
    Identifier --> Crowding
    Crowding --> TrainLoading
    Crowding --> PassengerFlow
    Place --> AdditionalProperties
    Place --> Place
