base_url = "https://api.tfl.gov.uk"
endpoints = {
    'Line_MetaModes': {'uri': '/Line/Meta/Modes', 'model': 'ModeArray'},
    'Line_MetaSeverity': {'uri': '/Line/Meta/Severity', 'model': 'ArrayOfStatusSeverities'},
    'Line_MetaDisruptionCategories': {'uri': '/Line/Meta/DisruptionCategories', 'model': 'ArrayOfStrings'},
    'Line_MetaServiceTypes': {'uri': '/Line/Meta/ServiceTypes', 'model': 'ArrayOfStrings'},
    'Line_GetByPathIds': {'uri': '/Line/{0}', 'model': 'ArrayOfLine'},
    'Line_GetByModeByPathModes': {'uri': '/Line/Mode/{0}', 'model': 'ArrayOfLine'},
    'Line_RouteByQueryServiceTypes': {'uri': '/Line/Route', 'model': 'ArrayOfLine'},
    'Line_LineRoutesByIdsByPathIdsQueryServiceTypes': {'uri': '/Line/{0}/Route', 'model': 'ArrayOfLine'},
    'Line_RouteByModeByPathModesQueryServiceTypes': {'uri': '/Line/Mode/{0}/Route', 'model': 'ArrayOfLine'},
    'Line_RouteSequenceByPathIdPathDirectionQueryServiceTypesQueryExcludeCrowding': {'uri': '/Line/{0}/Route/Sequence/{1}', 'model': 'RouteSequence'},
    'Line_StatusByPathIdsPathStartDatePathEndDateQueryDetail': {'uri': '/Line/{0}/Status/{1}/to/{2}', 'model': 'ArrayOfLine'},
    'Line_StatusByIdsByPathIdsQueryDetail': {'uri': '/Line/{0}/Status', 'model': 'ArrayOfLine'},
    'Line_SearchByPathQueryQueryModesQueryServiceTypes': {'uri': '/Line/Search/{0}', 'model': 'RouteSearchResponse'},
    'Line_StatusBySeverityByPathSeverity': {'uri': '/Line/Status/{0}', 'model': 'ArrayOfLine'},
    'Line_StatusByModeByPathModesQueryDetailQuerySeverityLevel': {'uri': '/Line/Mode/{0}/Status', 'model': 'ArrayOfLine'},
    'Line_StopPointsByPathIdQueryTflOperatedNationalRailStationsOnly': {'uri': '/Line/{0}/StopPoints', 'model': 'StopPointArray'},
    'Line_TimetableByPathFromStopPointIdPathId': {'uri': '/Line/{1}/Timetable/{0}', 'model': 'TimetableResponse'},
    'Line_TimetableToByPathFromStopPointIdPathIdPathToStopPointId': {'uri': '/Line/{1}/Timetable/{0}/to/{2}', 'model': 'TimetableResponse'},
    'Line_DisruptionByPathIds': {'uri': '/Line/{0}/Disruption', 'model': 'ArrayOfDisruptions'},
    'Line_DisruptionByModeByPathModes': {'uri': '/Line/Mode/{0}/Disruption', 'model': 'ArrayOfDisruptions'},
    'Line_ArrivalsWithStopPointByPathIdsPathStopPointIdQueryDirectionQueryDestina': {'uri': '/Line/{0}/Arrivals/{1}', 'model': 'PredictionArray'},
    'Line_ArrivalsByPathIds': {'uri': '/Line/{0}/Arrivals', 'model': 'PredictionArray'},
    'Forward_Proxy': {'uri': '/Line/*', 'model': 'ObjectResponse'},
}
